### ISSUE TITLE
VII. Keszthelyi Villanyautós Találkozó

### ISSUE THREAD

**Issue by oliverbacsi** [Sp3EdeR/autosesemenyek#1]
VII. Keszthelyi Villanyautós Találkozó

Immáron 7-edik alkalommal kerül megrendezésre az ősz legnagyobb szabású villanyautós találkozója Keszthelyen.
Időpont : 2024 szept 28 szombat
Helyszín : Délelőtt a Festetich-kastély parkja , délután a hajókikötő melletti teljes Balaton-part, promenád, platánfa-sor.

Várható : többszáz elektromos autó, általában a kastélyparkba be se fér mind, a szervezők egyazon típusból csak limitált létszámot engednek be, hogy minden típus képviseltethesse magát. Kiállítók, villanyautó-újdonságok, standok.
A szervezők részéről: Csoportos vezetett kastélylátogatás, résztvevőknek kedvezmények, a Balaton-parton óriáskerekezés, stb.
A résztvevők részéről: A villanyautósok nagyon nyitott és önzetlen közösség, a túlnyomó többség felajánlja a villanyautóját megtekintésre a látogatóknak, és minden érdeklődő kérdésre készséggel válaszolnak (100-adszor ugyanarra a kérdésre is).

**Comment by Sp3EdeR** [comment]
Mindenképpen szükséges Facebook esemény link, anélkül nem lehet felvenni a naptárba. Leírás nem szükséges, mert direktben a Facebookkal szinkronizál a naptár.

**Comment by oliverbacsi** [comment]
Az ilyen korán még nincs létrehozva, általában az előző évi van megeditálva és átnevezve.
Jelenleg csak a VI. találkozó eseménye van meg, 2023 szeptemberére.
Ha meglesz, bedobom a linket.

**Comment by Sp3EdeR** [comment]
Tökéletes @oliverbacsi, az jó lesz. Addig zárom akkor ezt a jegyet. Ha elkészül, akkor jöhet új jegyben. :)
