### ISSUE TITLE
IV. Villanyautós Családi Nap Gyenesdiás

### ISSUE THREAD

**Issue by oliverbacsi** [Sp3EdeR/autosesemenyek#2]
IV. Villanyautós Családi Nap Gyenesdiás

Facebook link : https://www.facebook.com/events/1432455137482486
Dátum : 2024. 04. 20. Szombat
Helyszín : A Gyenesdiás fölötti Nagymező. (erdei tisztás)
A részvétel regisztrációs lap kitöltéséhez kötött, de ingyenes. A Nagymező területére csak regisztrált autó hajthat be, a nézelődőknek a parkolóban kell lerakni az autóikat.
Ez az esemény a családokra és gyerekekre van optimalizálva, vezetett családias túrák szakképzett túravezetővel a környező kilátóhoz, barlanghoz. A réten modellbemutatók, gulyásfőzés, huszárbemutató, ágyú- és kováspuska elsütés, dobosok bemutatója, általában a gyenesdiási "Rügyfakasztó" falunap eseményeivel van összevonva. Gyerekeknek nagy játszótér, elektromos autóról üzemeltetett ugrálóvár, stb.
Kiállítók, standok általában nincsenek, a nézelődőknek a résztvevők mutatják be saját autóikat és minden kérdésre válaszolnak.
Mivel a Nagymezőn gyerekek és családok mozognak, így ott autós élvezkedés nincs, az autós élmény részét az képezi, hogy általában reggel a balatongyöröki Szépkilátón van a találkozó, és közös átvonulás van Gyenesdiásra.

**Comment by Sp3EdeR** [comment]
Az esemény hozzáadva, pár órán belül felkerül a listára. (Nem szükséges eseményleírás, elég a Facebook link. Direktben a Facebookkal szinkronizál a naptár.)
