### ISSUE TITLE
Elektromos jármű-tulajdonosok találkozója, Tordas

### ISSUE THREAD

**Issue by oliverbacsi** [Sp3EdeR/autosesemenyek#3]
Elektromos jármű-tulajdonosok találkozója, Tordas

facebook link : https://www.facebook.com/events/376502711828276
Helyszín: Tordasi Western-falu, élményfalu
Időpont: 2023. 03. 23.   08:00 és 14:00 , zárás 20:00

08:00-tól "Alba Challenge" (a 100 pontos challenge egy változata) . Autós , GPS-es pontkeresés, akadályverseny
14:00-tól Elektromos autós találkozó, kötetlen beszélgetés, tapaszalatcsere, elektromos autók iránt érdeklődők felvilágosítása.
Szervező a Magyar Elektromobilitás Egyesület (web: elmob.hu)

**Comment by Sp3EdeR** [comment]
Az esemény hozzáadva, pár órán belül felkerül a listára.
